server:
  port: 8080

test:
  hello: 'hello application'
#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wikidev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wikiUser
    password: wiki
    driver-class-name: com.mysql.cj.jdbc.Driver


#配置mybatis所有mapper.xml所在的路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml