server:
  port: 8080

test:
  hello: 'hello application'
#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: wikiUser
    password: wiki
    driver-class-name: com.mysql.cj.jdbc.Driver